### ISSUE TITLE
Export Notes into a Single Database File

### ISSUE THREAD

**Issue by moriel5** [SecUSo/privacy-friendly-notes#67]
Could we have an option to back up all notes into a single .db file, similar to how "Just Note" does it?

This is the only thing currently preventing me from switching over to "Privacy Notes".

Otherwise, this is the best notes app I have seen at this size (I have an obsession with lightweight apps, as such, I think that 5MB is too heavy for a note taking app).

**Comment by dkavlakov** [comment]
Double on this.
I actually made the mistake of switching and using it actively. Now I am forced to carry around old phone with failed touchscreen and Bluetooth mouse just to be able to access my notes. Can't even give it for repair because of the data loss risk.

**Comment by Kamuno** [comment]
Related: #28 #38 #33

**Comment by T-vK** [comment]
You can follow this #94 and create a tar archive from the exported files, if you want to export and only have a single file.

**Comment by moriel5** [comment]
> You can follow this #94 and create a tar archive from the exported files, if you want to export and only have a single file.

Thanks, that is intriguing (as I generally do root my devices, I could follow those instructions), however not everyone roots their phones, so this is not a real answer to the problem.

**Comment by Kamuno** [comment]
We used this approach as well in the past.. you can also extract the data on not rooted devices via adb.. 
But we just integrated the notes app with the backup app so you can export your data without the need of a rooted device or special knowledge.

This update should be released very soon. The current version on the master branch should already allow you to do that. However the backup app will need an update to support the version installed from the f-droid store. So this will take a little bit longer due to the checks being performed.

**Comment by moriel5** [comment]
Alright, that does seem sound, I'll make sure to test it out next week when I have the time.

**Comment by coderPaddyS** [comment]
As we implemented the backup functionality via Privacy Friendly Backup, this issue will be closed.
